### PR TITLE
Fix quoted paths, relative paths, and option order dependence (+ tests) 

### LINKED ISSUE #79: Quoted plugin path issue on 1.0.0 beta
It looks like the following won't work on 1.0.0

```
~/Downloads/pluginval-20.app/Contents/MacOS/pluginval --validate "~/Library/Audio/Plug-Ins/Components/Playground.component"
```

Pluginval says it can't find the plugin:

```
Num plugins found: 0
!!! Test 1 failed: No types found. This usually means the plugin binary is missing or damaged, an incompatible format or that it is an AU that isn't found by macOS so can't be created.
FAILED!!  1 test failed, out of a total of 1
*** FAILED
```

Without the quotes it's happy:

```
~/Downloads/pluginval-20.app/Contents/MacOS/pluginval --validate ~/Library/Audio/Plug-Ins/Components/Playground.component
```

This makes it a bit tougher to specify paths with spaces in them, such as:

```
"~/Library/Audio/Plug-Ins/Components/My Plugin.component"
```

(it works with the space escaped by a backslash)

### PR DESCRIPTION
**Pull request by sudara**
Closes #79.

Waiting to go green here: https://github.com/sudara/pluginval/actions/runs/2720056546

Quoting paths to `--validate` doesn't work in 1.0, so the following fail, making it hard to work with filenames with spaces:

```
# Quoted relative paths 
pluginval --validate "~/Library/Audio/Plug-Ins/Components/Plugin.component"         
pluginval --validate "~/Library/Audio/Plug-Ins/Components/Sine Machine.component"         

# Quoted absolute paths
pluginval --validate "/Users/sudara/Library/Audio/Components/Sine Machine.component"
```

I think a few other relative path edge cases were failing too, but I don't quite remember now. The `fileOrID` variable wasn't being used in `parseCommandLine`'s return value. 

I followed [the best practice as described in this assert](https://github.com/juce-framework/JUCE/blob/master/modules/juce_core/files/juce_File.cpp#L200-L207) for constructing relative paths and added tests for many permutations of paths and ids.

Note:  `--run-tests` doesn't produce seem any test output on Windows pluginval 1.0 (beyond logging the # failed), so it's a bit tough to debug test failures there at the moment.

### CODE REVIEW

File: Source/CommandLine.cpp [hunk 1]
```diff
@@ -462,10 +462,18 @@ bool shouldPerformCommandLine (const String& commandLine)
 //==============================================================================
 std::pair<juce::String, PluginTests::Options> parseCommandLine (const juce::ArgumentList& args)
 {
+    // prioritize explicit arguments
     auto fileOrID = args.getValueForOption ("--validate");
 
+    // but let user lazily supply the plugin path as the last arg
+    if (fileOrID.isEmpty())
```
Comment (drowaudio) [inline Source/CommandLine.cpp:469]: I don't think this should be needed as the `ArgumentList` supplied should already be formatted to add the `--validate` option before an implicit plugin path for the last arg?

**Review by drowaudio — COMMENTED** [review]
Just one comment I'm not sure about here...

File: Source/CommandLine.cpp (hunk 1 above)
Comment (sudara) [reply Source/CommandLine.cpp:469]: This confused me as well, but I assumed there was some reason the existing logic using `args.arguments.getLast()`...

Just took a deeper look and it's because [`getValueForOption` only returns a value when it matches an equal sign for long arguments](https://github.com/juce-framework/JUCE/blob/master/modules/juce_core/misc/juce_ConsoleApplication.cpp#L97-L108). So, the string would have to be `--validate=some/plugin/path` to work correctly. It seems to always be empty here otherwise.

This sorta motivates me more to look into CLI11 down the line... the JUCE option parsing seems a bit crusty/hard to use and the `getLast` call is likely also [why this bug exists](https://forum.juce.com/t/anouncing-pluginval-an-open-source-cross-platform-plugin-validation-tool/27710/191?u=sudara).

Seeing if i can find a solution...

Comment (sudara) [reply Source/CommandLine.cpp]: Ok, so it seems to be a lose-lose situation unless we embrace the fact that JUCE wants to see `--validate=/some/path`. 

I updated the PR with how I would resolve this (rewriting the implicit and explicit validate case).

This also resolves the order independence bug, which I added a test for.

File: Source/CommandLine.cpp [hunk 2]
```diff
@@ -409,8 +409,25 @@ static ArgumentList createCommandLineArgs (String commandLine)
                                                 || argList.containsOption ("--run-tests");
 
         if (! hasValidateOrOtherCommand)
-            if (isPluginArgument (argList.arguments.getLast().text))
-                argList.arguments.insert (argList.arguments.size() - 1, { "--validate" });
+        {
```
Comment (drowaudio) [inline Source/CommandLine.cpp:412]: I don't think you need these changes [412 - 430].
All this code should do is if "--validate" is not in the args AND the last argument looks like a plugin path (`isPluginArgument`), then insert a `--validate` argument before it.

The actual "fix" for the original issue is below on line 482.

File: Source/CommandLine.cpp [hunk 3]
```diff
@@ -464,8 +481,11 @@ std::pair<juce::String, PluginTests::Options> parseCommandLine (const juce::Argu
 {
     auto fileOrID = args.getValueForOption ("--validate");
```
Comment (drowaudio) [inline Source/CommandLine.cpp:482]: This is the bit that actually needs to be fixed. Instead of using the `juce::ArgumentList::getValueForOption`, it should use my `getOptionValue`, in the same way as elsewhere in the file: `auto fileOrID = getOptionValue (args, "--validate", "", "Expected a plugin path for the --validate option").toString();`

**Review by drowaudio — CHANGES_REQUESTED** [review]
I've proposed a smaller change which I think should pass all the tests without hacking in the juce `=` syntax.

**Comment by sudara** [comment]
I see... you wrote custom logic to support `=`-less options across the board, which treats the next "option" as the first option's value, bypassing JUCE's option/value logic.

In that case, switching out `getLast` with `getOptionValue` makes sense to me, I'll make the change.

**Comment by sudara** [comment]
Ok, swapped it out with `getOptionValue`, the build is here: https://github.com/sudara/pluginval/actions/runs/2720056546

`File::getCurrentWorkingDirectory().getChildFile(fileOrID).getFullPathName();` seems necessary to make relative paths (~ and ./) happy.
